import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

const defaultTools = [
  {
    toolName: "Unity",
    version: "2023 LTS",
    provider: "Unity Technologies",
    license: "Personal (Free) / Pro (Paid)",
    category: "game_engine",
    description: "2D ve 3D oyun geliştirme motoru",
    apiSupport: true,
    cliSupport: true,
    capabilities: JSON.stringify(["2D", "3D", "AR", "VR", "multiplayer", "physics"]),
    riskLevel: "MEDIUM",
    isFree: true,
    costDescription: "Kişisel kullanım ücretsiz, Pro $2,040/yıl",
    integrationStatus: "planned",
  },
  {
    toolName: "Godot",
    version: "4.3",
    provider: "Godot Foundation",
    license: "MIT (Açık Kaynak)",
    category: "game_engine",
    description: "Açık kaynak 2D ve 3D oyun motoru",
    apiSupport: true,
    cliSupport: true,
    capabilities: JSON.stringify(["2D", "3D", "multiplayer", "scripting", "animation"]),
    riskLevel: "LOW",
    isFree: true,
    costDescription: "Tamamen ücretsiz",
    integrationStatus: "planned",
  },
  {
    toolName: "Blender",
    version: "4.2",
    provider: "Blender Foundation",
    license: "GPL (Açık Kaynak)",
    category: "3d_modeling",
    description: "3D modelleme, animasyon, render, video düzenleme",
    apiSupport: true,
    cliSupport: true,
    capabilities: JSON.stringify(["modeling", "sculpting", "animation", "rendering", "texturing"]),
    riskLevel: "LOW",
    isFree: true,
    costDescription: "Tamamen ücretsiz",
    integrationStatus: "planned",
  },
  {
    toolName: "VS Code",
    version: "1.95",
    provider: "Microsoft",
    license: "MIT (Açık Kaynak)",
    category: "ide",
    description: "Kod editörü",
    apiSupport: false,
    cliSupport: true,
    capabilities: JSON.stringify(["editing", "debugging", "git", "extensions", "terminal"]),
    riskLevel: "LOW",
    isFree: true,
    costDescription: "Tamamen ücretsiz",
    integrationStatus: "active",
  },
  {
    toolName: "Git",
    version: "2.47",
    provider: "Git Community",
    license: "GPL (Açık Kaynak)",
    category: "version_control",
    description: "Dağıtık versiyon kontrol sistemi",
    apiSupport: false,
    cliSupport: true,
    capabilities: JSON.stringify(["versioning", "branching", "merging", "collaboration"]),
    riskLevel: "LOW",
    isFree: true,
    costDescription: "Tamamen ücretsiz",
    integrationStatus: "active",
  },
  {
    toolName: "Docker",
    version: "27.x",
    provider: "Docker Inc.",
    license: "Apache 2.0 (Personal Free)",
    category: "containerization",
    description: "Konteyner tabanlı sanallaştırma platformu",
    apiSupport: true,
    cliSupport: true,
    capabilities: JSON.stringify(["containerization", "isolation", "deployment", "orchestration"]),
    riskLevel: "MEDIUM",
    isFree: true,
    costDescription: "Kişisel kullanım ücretsiz",
    integrationStatus: "active",
  },
  {
    toolName: "Photopea",
    version: "Online",
    provider: "Photopea",
    license: "Freemium",
    category: "image_editing",
    description: "Tarayıcı tabanlı Photoshop alternatifi",
    apiSupport: false,
    cliSupport: false,
    capabilities: JSON.stringify(["layers", "filters", "masks", "psd_support"]),
    riskLevel: "LOW",
    isFree: true,
    costDescription: "Reklam destekli ücretsiz, Premium $5/ay",
    integrationStatus: "planned",
  },
  {
    toolName: "remove.bg",
    version: "API v1",
    provider: "remove.bg",
    license: "API (Freemium)",
    category: "image_editing",
    description: "Görsellerden arka plan silme aracı",
    apiSupport: true,
    cliSupport: false,
    capabilities: JSON.stringify(["background_removal", "batch_processing"]),
    riskLevel: "LOW",
    isFree: false,
    costDescription: "50 görsel/ay ücretsiz, sonrası kredi başına ücretli",
    integrationStatus: "planned",
  },
];

export async function GET() {
  let added = 0;
  for (const tool of defaultTools) {
    const exists = await prisma.toolRegistry.findUnique({ where: { toolName: tool.toolName } });
    if (!exists) {
      await prisma.toolRegistry.create({ data: tool });
      added++;
    }
  }
  return NextResponse.json({ message: "Tool Registry seeded", added, total: defaultTools.length });
}